name: Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build
        run: ./gradlew clean build --refresh-dependencies --parallel

      - name: Generate Coverage Report
        run: ./gradlew jacocoAggregateReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        with:
          file: ./build/reports/jacoco/jacocoAggregateReport/jacocoAggregateReport.xml

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs